### ISSUE TITLE
ExoPlayerImplInternal Source error

### ISSUE THREAD

**Issue by BZ-ramzi** [vadootvpeer/sdk-android#1]
Hello, can you help me for solve the problem?

![image](https://user-images.githubusercontent.com/14264869/96736651-1a8b1000-13bd-11eb-8100-4ec3e7fe9d78.png)

**Comment by vadootvpeer** [comment]
Can you share the video stream url which you are trying to play ?

**Comment by vadootvpeer** [comment]
Closing the issue due to inactivity. Open it again if the issue is persistent

**Comment by vadootvpeer** [comment]
Closing the issue due to inactivity. Open it again if the issue is persistent
