### ISSUE TITLE
How i can test p2p ?

### ISSUE THREAD

**Issue by BZ-ramzi** [vadootvpeer/sdk-android#2]
How i can test the p2p function ? how many users are needed to operate p2p ?

![image](https://user-images.githubusercontent.com/14264869/96738277-d6007400-13be-11eb-99c5-079235e81be3.png)

**Comment by vadootvpeer** [comment]
The demo apk can be used to test p2p https://github.com/vadootvpeer/sdk-android/blob/master/sample_apps/VadooDemo/VadooDemo.apk . Also the sample code is provided open-source. The web demo is available at http://api.peervadoo.com/test to check out.

Sample code of the demo android app is available at https://github.com/vadootvpeer/sdk-android/tree/master/sample_apps/VadooDemo . Replace the token and keep your own url to start testing. If you face issues let me know.

**Comment by vadootvpeer** [comment]
Closing the issue due to inactivity. Open it again if the issue is persistent
